import unittest

def jogoDaVida(linhas, colunas, mundo):
    proxGeracao = '''........
...**...
...**...
........'''
    return proxGeracao
    

class StubTests(unittest.TestCase):    
    def testJDV_4_8_mundo1(self):
        mundoGeracao2 = '''........
...**...
...**...
........'''
        mundoGeracao1 = '''........
....*...
...**...
........'''
        self.assertEquals(mundoGeracao2, jogoDaVida(4, 8, mundoGeracao1))

if __name__ == '__main__':
    unittest.main()

